fallback to root

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/homebridge/run b/rootfs/etc/s6-overlay/s6-rc.d/homebridge/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/homebridge/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/homebridge/run
@@ -7,10 +7,19 @@ export HOMEBRIDGE_CONFIG_UI=1
 # this is not necessarily the ui version, it's used as a feature compatibility indicator 
 export CONFIG_UI_VERSION=4.44.2
 
-# fix permissions
-chown -R homebridge: /homebridge /opt/homebridge
-
-# change pwd
+# change cwd
 cd /homebridge
 
-exec s6-setuidgid homebridge /opt/homebridge/start.sh 
+# fix permissions on /opt/homebridge
+chown -R homebridge: /opt/homebridge
+
+# fix permissions on /homebridge
+chown -R homebridge: /homebridge 
+if [ "$?" != "0" ]; then
+  # if we can't set permissions on /homebridge, run Homebridge as root, it's not ideal, but it's better than nothing
+  echo "Failed to set permissions on /homebridge to $PUID:$PGID; the Homebridge service will run as root."
+  exec /opt/homebridge/start.sh --allow-root
+else
+  # standard operation, run as homebridge user
+  exec s6-setuidgid homebridge /opt/homebridge/start.sh 
+fi
