Dependabot, beta and package.json

diff --git a/.github/workflows/build_and_push.yml b/.github/workflows/build_and_push.yml
--- a/.github/workflows/build_and_push.yml
+++ b/.github/workflows/build_and_push.yml
@@ -3,14 +3,18 @@ name: Build and Push Docker Images
 on:
   release:
     types: [published]
+  workflow_dispatch:
+    inputs:
+      logLevel:
+        description: 'Triggers a beta release of the Homebridge Docker image. The image will be built using versions from beta/package.json and tagged with "beta" and "beta-YYYY-MM-DD" (e.g., beta-2025-06-17). Images will be pushed to ghcr.io/homebridge/homebridge and, if configured, homebridge/homebridge on Docker Hub.'
+        required: false
+        default: 'info'
 
 jobs:
-  # build all the image variants
   build:
     runs-on: ubuntu-latest
 
     steps:
-    # checkout repo
     - name: Checkout
       uses: actions/checkout@v4
 
@@ -23,7 +27,11 @@ jobs:
     - name: Get branch/tag name
       id: get_branch
       run: |
-        export BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g" -e "s/refs\/tags\///g")
+        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+          export BRANCH_NAME="beta-$(date +%Y-%m-%d)"
+        else
+          export BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g" -e "s/refs\/tags\///g")
+        fi
         echo $BRANCH_NAME
         echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
 
@@ -49,18 +57,34 @@ jobs:
         echo $VERSION_IMAGE_TAG
         echo "VERSION_IMAGE_TAG=${VERSION_IMAGE_TAG}" >> $GITHUB_OUTPUT
 
+    - name: Check for beta release
+      id: check_beta
+      run: |
+        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+          if [[ -f beta/package.json ]]; then
+            echo "IS_BETA=true" >> $GITHUB_OUTPUT
+          else
+            echo "Error: beta/package.json is missing for beta release"
+            exit 1
+          fi
+        else
+          echo "IS_BETA=false" >> $GITHUB_OUTPUT
+        fi
+
     - name: Set Package Versions
       id: pkg_version
       run: |
-        get_latest_release() {
-          curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
-            grep '"tag_name":' |                                            # Get tag line
-            sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
-        }
-        export HOMEBRIDGE_APT_PKG_VERSION=`get_latest_release "homebridge/homebridge-apt-pkg"`
-        export FFMPEG_VERSION=`get_latest_release "homebridge/ffmpeg-for-homebridge"`
-        echo "HOMEBRIDGE_APT_PKG_VERSION=${HOMEBRIDGE_APT_PKG_VERSION}" >> $GITHUB_OUTPUT
-        echo "FFMPEG_VERSION=${FFMPEG_VERSION}" >> $GITHUB_OUTPUT
+        if [[ "${{ steps.check_beta.outputs.IS_BETA }}" == "true" ]]; then
+          export HOMEBRIDGE_APT_PKG_VERSION=$(jq -r '.dependencies["@homebridge/homebridge-apt-pkg"]' beta/package.json | sed 's/\^//')
+          export FFMPEG_FOR_HOMEBRIDGE_VERSION=$(jq -r '.dependencies["ffmpeg-for-homebridge"]' beta/package.json | sed 's/\^//')
+        else
+          export HOMEBRIDGE_APT_PKG_VERSION=$(jq -r '.dependencies["@homebridge/homebridge-apt-pkg"]' package.json | sed 's/\^//')
+          export FFMPEG_FOR_HOMEBRIDGE_VERSION=$(jq -r '.dependencies["ffmpeg-for-homebridge"]' package.json | sed 's/\^//')
+        fi
+        export DOCKER_HOMEBRIDGE_VERSION=${{ steps.image_tag.outputs.IMAGE_TAG }}
+        echo "HOMEBRIDGE_APT_PKG_VERSION=v${HOMEBRIDGE_APT_PKG_VERSION}" >> $GITHUB_OUTPUT
+        echo "FFMPEG_FOR_HOMEBRIDGE_VERSION=v${FFMPEG_FOR_HOMEBRIDGE_VERSION}" >> $GITHUB_OUTPUT
+        echo "DOCKER_HOMEBRIDGE_VERSION=${DOCKER_HOMEBRIDGE_VERSION}" >> $GITHUB_OUTPUT
 
     - name: Log into GitHub Container registry
       uses: docker/login-action@v3
@@ -69,7 +93,8 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
 
-    - name: Build and Push Image to GitHub Container Registry
+    - name: Build and Push Image to GitHub Container Registry (Stable)
+      if: steps.check_beta.outputs.IS_BETA == 'false'
       uses: docker/build-push-action@v5
       with:
         context: .
@@ -78,10 +103,27 @@ jobs:
         push: true
         build-args: |
           HOMEBRIDGE_APT_PKG_VERSION=${{ steps.pkg_version.outputs.HOMEBRIDGE_APT_PKG_VERSION }}
-          FFMPEG_VERSION=${{ steps.pkg_version.outputs.FFMPEG_VERSION }}
+          FFMPEG_FOR_HOMEBRIDGE_VERSION=${{ steps.pkg_version.outputs.FFMPEG_FOR_HOMEBRIDGE_VERSION }}
+          DOCKER_HOMEBRIDGE_VERSION=${{ steps.image_tag.outputs.IMAGE_TAG }}
         tags: |
           ghcr.io/homebridge/homebridge:latest
           ghcr.io/homebridge/homebridge:ubuntu
+          ghcr.io/homebridge/homebridge:${{ steps.image_tag.outputs.IMAGE_TAG }}
+
+    - name: Build and Push Image to GitHub Container Registry (Beta)
+      if: steps.check_beta.outputs.IS_BETA == 'true'
+      uses: docker/build-push-action@v5
+      with:
+        context: .
+        file: ./Dockerfile
+        platforms: linux/amd64,linux/arm/v7,linux/arm64
+        push: true
+        build-args: |
+          HOMEBRIDGE_APT_PKG_VERSION=${{ steps.pkg_version.outputs.HOMEBRIDGE_APT_PKG_VERSION }}
+          FFMPEG_FOR_HOMEBRIDGE_VERSION=${{ steps.pkg_version.outputs.FFMPEG_FOR_HOMEBRIDGE_VERSION }}
+          DOCKER_HOMEBRIDGE_VERSION=${{ steps.image_tag.outputs.IMAGE_TAG }}
+        tags: |
+          ghcr.io/homebridge/homebridge:beta
           ghcr.io/homebridge/homebridge:${{ steps.image_tag.outputs.IMAGE_TAG }}
 
     - name: Log into Docker Hub
@@ -92,9 +134,9 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Build and Push Image to Docker Hub
+    - name: Build and Push Image to Docker Hub (Stable)
+      if: github.repository == 'homebridge/docker-homebridge' && steps.check_beta.outputs.IS_BETA == 'false'
       uses: docker/build-push-action@v5
-      if: github.repository == 'homebridge/docker-homebridge'
       with:
         context: .
         file: ./Dockerfile
@@ -102,15 +144,43 @@ jobs:
         push: true
         build-args: |
           HOMEBRIDGE_APT_PKG_VERSION=${{ steps.pkg_version.outputs.HOMEBRIDGE_APT_PKG_VERSION }}
-          FFMPEG_VERSION=${{ steps.pkg_version.outputs.FFMPEG_VERSION }}
+          FFMPEG_FOR_HOMEBRIDGE_VERSION=${{ steps.pkg_version.outputs.FFMPEG_FOR_HOMEBRIDGE_VERSION }}
+          DOCKER_HOMEBRIDGE_VERSION=${{ steps.image_tag.outputs.IMAGE_TAG }}
         tags: |
           homebridge/homebridge:latest
           homebridge/homebridge:ubuntu
           homebridge/homebridge:${{ steps.image_tag.outputs.IMAGE_TAG }}
 
+    - name: Build and Push Image to Docker Hub (Beta)
+      if: github.repository == 'homebridge/docker-homebridge' && steps.check_beta.outputs.IS_BETA == 'true'
+      uses: docker/build-push-action@v5
+      with:
+        context: .
+        file: ./Dockerfile
+        platforms: linux/amd64,linux/arm/v7,linux/arm64
+        push: true
+        build-args: |
+          HOMEBRIDGE_APT_PKG_VERSION=${{ steps.pkg_version.outputs.HOMEBRIDGE_APT_PKG_VERSION }}
+          FFMPEG_FOR_HOMEBRIDGE_VERSION=${{ steps.pkg_version.outputs.FFMPEG_FOR_HOMEBRIDGE_VERSION }}
+          DOCKER_HOMEBRIDGE_VERSION=${{ steps.image_tag.outputs.IMAGE_TAG }}
+        tags: |
+          homebridge/homebridge:beta
+          homebridge/homebridge:${{ steps.image_tag.outputs.IMAGE_TAG }}
+
+    - name: Send Discord Notification
+      uses: appleboy/discord-action@master
+      with:
+        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
+        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
+        message: |
+          **Homebridge Docker Release**
+          Version: ${{ github.event_name == 'workflow_dispatch' && format('beta-{0}', steps.versioned_image_tag.outputs.VERSION_IMAGE_TAG) || github.event.release.tag_name }}
+          [View Release](https://github.com/homebridge/docker-homebridge/releases/tag/${{ github.event_name == 'workflow_dispatch' && format('beta-{0}', steps.versioned_image_tag.outputs.VERSION_IMAGE_TAG) || github.event.release.tag_name }})
+
   tag:
     name: Verify Release Tag
     runs-on: ubuntu-latest
+    if: github.event_name == 'release'
     outputs:
       version: ${{ steps.get_version.outputs.version }}
     steps:
@@ -131,16 +201,4 @@ jobs:
           echo Latest Tag does not matches Release tag
           exit 1  
       - name: Published
-        run: echo "::notice::GitHub Release - https://github.com/homebridge/docker-homebridge/releases/tag/${{ github.event.release.tag_name }}" 
-
-  github-releases-to-discord:
-    name: Discord Webhooks
-    needs: build
-    uses: homebridge/.github/.github/workflows/discord-webhooks.yml@latest
-    with:
-      title: "Homebridge Docker Release"
-      description: |
-        Version `${{ github.event.release.tag_name }}`
-      url: "https://github.com/homebridge/docker-homebridge/releases/tag/${{ github.event.release.tag_name }}"
-    secrets:
-      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_LATEST }}
+        run: echo "::notice::GitHub Release - https://github.com/homebridge/docker-homebridge/releases/tag/${{ github.event.release.tag_name }}"
